-- AlterTable
ALTER TABLE "user_badges" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "image" DROP NOT NULL;

-- AlterTable
ALTER TABLE "user_details" ALTER COLUMN "avatar" DROP NOT NULL,
ALTER COLUMN "time_worked_out" SET DEFAULT 0,
ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "streak" SET DEFAULT 0,
ALTER COLUMN "weight" SET DEFAULT 0,
ALTER COLUMN "height" SET DEFAULT 0,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "gender" SET DEFAULT 'Null',
ALTER COLUMN "age" SET DEFAULT 0;
